### ISSUE TITLE
Use Boost from AppVeyor

### ISSUE THREAD

**Issue by hmenke** [pairinteraction/pairinteraction-build-dependencies#1]
Currently we are compiling Boost from source using VCPKG.  This takes *forever*.  AppVeyor already provides Boost, so why not use this?  It is easy to use in `.appveyor.yml`, e.g. at the top level:
```yaml
environment:
  BOOST_ROOT: "C:\\Libraries\\boost_1_60_0"
  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_60_0\\lib64-msvc-14.0"
  PATH: "%BOOST_LIBRARYDIR%;%PATH%"
```
I can report that this works just fine in other projects of mine:
https://github.com/hmenke/cpp-patterns/blob/master/.appveyor.yml
https://github.com/hmenke/boost_matheval/blob/master/.appveyor.yml
